#!/bin/sh
# set -ex
for FILE in `find . -not -path '*/\.*'`; do
    LINE_NUMBER=`sed -n "/[bump when prefix is:[ ]+.*\]/=" $FILE`

    PREFIX=`sed -n -E 's/.*\[bump when prefix is:[ ]+(.*)\]/\1/p' $FILE`

    if [ "$PREFIX" = "$TAG_PREFIX" ]; then
        LINE_NUMBER=`let 'LINE_NUMBER++'`
        sed -i -E "${LINE_NUMBER}s/(.*)([0-9]+\.[0-9]+\.[0-9]+)(.*)/\1${VERSION}\3/g" $FILE
    fi
done
