#!/bin/sh

set -e

[ -z $VERSION_FILE ] && VERSION_FILE=./VERSION
[ \( -z "$REPOSITORY" \) -a \( ! -z "$CIRCLE_PROJECT_REPONAME" \) ] && REPOSITORY="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
[ -f $VERSION_FILE ] || (echo "file containing current version is needed, default is ./VERSION, customizable with VERSION_FILE env var" && exit 1)
[ -z "$REPOSITORY" ] && (echo "env var REPOSITORY is needed when executing outside of circleci, (for exampe REPOSITORY=user/repo)" && exit 1)

git config  user.email "bump@version.com"
git config  user.name "bump-version"

git checkout master
git pull --commit --no-edit https://${GITHUB_TOKEN}@github.com/${REPOSITORY}.git master

# bump version
[ -z "$GIT_CHECK" ] || /suitable $GIT_CHECK && CONTINUE=1

[ -n "$CONTINUE" ] || exit 0

[ -n "$TAG_PREFIX" ] || /_sed
[ -z "$TAG_PREFIX" ] || /_sed_with_prefix

(/script/bump --filename $VERSION_FILE)
VERSION=`cat $VERSION_FILE`

git add $VERSION_FILE
git commit -m "${TAG_PREFIX} ${VERSION}" -m "[skip ci]"
git tag "${TAG_PREFIX}${VERSION}"
git push  --tags  https://${GITHUB_TOKEN}@github.com/${REPOSITORY}.git HEAD
