#!/bin/sh

set -e

[ -f ./VERSION ] || (echo "file VERSION containing current version is needed" && exit 1)
[ -f ./setup.py ] || (echo "file setup.py is required" && exit 1)
[ -z $USERNAME ] && (echo "env var USERNAME is required" && exit 1)
[ -z $PASSWORD ] && (echo "env var PASSWORD is required" && exit 1)

git config user.name "deploy docker"
git config user.email "deploy@docker.com"

git checkout master
git pull --commit --no-edit https://${GITHUB_TOKEN}@github.com/${REPOSITORY}.git master

[ -z "$GIT_CHECK" ] || /suitable $GIT_CHECK && CONTINUE=1

[ -z "$CONTINUE" ] && exit 0

python setup.py sdist bdist_wheel

python -m twine upload -u $USERNAME -p $PASSWORD  dist/*
