#!/bin/sh

set -e

[ \( -z "$REPOSITORY" \) -a \( ! -z "$CIRCLE_PROJECT_REPONAME" \) ] && REPOSITORY="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
[ -f ./VERSION ] || (echo "file VERSION containing current version is needed" && exit 1)
[ -z "$REPOSITORY" ] && (echo "env var REPOSITORY is needed when executing outside of circleci, (for exampe REPOSITORY=user/repo)" && exit 1) 

git config  user.email "bump@version.com"
git config  user.name "bump-version"

git checkout master
git pull --commit --no-editor https://${GITHUB_TOKEN}@github.com/${REPOSITORY}.git master

# bump version
python -c '\
version = open("VERSION", "r").read().strip()
new = version.split(".")[-1]
new = int(new) + 1
new = ".".join(version.split(".")[:-1]) + "." + str(new)
open("VERSION", "w").write(new)
'


version=`cat VERSION`


git add VERSION
git commit -m "version $version" -m "[skip ci]"
git tag  "$version"
git push  --tags  https://${GITHUB_TOKEN}@github.com/${REPOSITORY}.git HEAD