
version: 2
jobs:

    deploy:
        docker:
            - image: xmorse/deploy-docker:0.4.0
        steps:
            - checkout
            - setup_remote_docker
            - run:
               command:  "[ `sh .circleci/suitable.sh ./deploy-docker` ] && (cd deploy-docker && /deploy)"
               environment: 
                  REGISTRY: docker.io
                  IMAGE_NAME: cistuff/deploy-docker
            - run: 
               command: "[ `sh .circleci/suitable.sh ./deploy-pypi` ] && (cd deploy-pypi && /deploy)"
               environment: 
                  REGISTRY: docker.io
                  IMAGE_NAME: cistuff/deploy-pypi
            - run: 
               command: "[ `sh .circleci/suitable.sh ./bump-version` ] && (cd bump-version && /deploy)"
               environment: 
                  REGISTRY: docker.io
                  IMAGE_NAME: cistuff/bump-version
    bump:
        docker:
            - image: xmorse/bump-version
        steps:
            - checkout
            - run:
               command: "[ `sh .circleci/suitable.sh ./deploy-docker` ] && (cd deploy-docker && /bump)"
            - run: 
               command: "[ `sh .circleci/suitable.sh ./deploy-pypi` ] && (cd deploy-pypi && /bump)"
            - run: 
               command: "[ `sh .circleci/suitable.sh ./bump-version` ] && (cd bump-version && /bump)"

workflows:
    version: 2
    test_and_deploy:
        jobs:
            - bump
            - deploy:
                requires:
                    - bump