
version: 2
jobs:

    deploy:
        docker:
            - image: cistuff/deploy-docker:1.0.10
        environment:
            GIT_CHECK: ./
            REGISTRY: docker.io
        steps:
            - checkout
            - setup_remote_docker
            - run:
               name: push deploy-docker
               command: cd deploy-docker && /deploy
               environment: 
                  IMAGE_NAME: cistuff/deploy-docker
            - run: 
               name: push deploy-pypi
               command: cd deploy-pypi && /deploy
               environment: 
                  IMAGE_NAME: cistuff/deploy-pypi
            - run: 
               name: push deploy-npm
               command: cd deploy-npm && /deploy
               environment: 
                  IMAGE_NAME: cistuff/deploy-npm
            - run: 
               name: push bump
               command: cd bump && /deploy
               environment: 
                  IMAGE_NAME: cistuff/bump
    bump:
        environment:
            VERSION_FILE: ./VERSION
            GIT_CHECK: ./
        docker:
            - image: cistuff/bump:1.0.8
        steps:
            - checkout
            - run:
               environment:
                  TAG_PREFIX: deploy-docker_
               name: bump deploy-docker
               command: cd deploy-docker && /bump
            - run: 
               environment:
                  TAG_PREFIX: deploy-pypi_
               name: bump deploy-pypi
               command: cd deploy-pypi && /bump
            - run:
               environment:
                  TAG_PREFIX: deploy-npm_
               name: bump deploy-npm
               command: cd deploy-npm && /bump
            - run:
               environment:
                  TAG_PREFIX: bump_
               name: bump bump
               command: cd bump && /bump

workflows:
    version: 2
    test_and_deploy:
        jobs:
            - bump
            - deploy:
                requires:
                    - bump