
version: 2
jobs:

    deploy:
        docker:
            - image: cistuff/deploy-docker
        steps:
            - checkout
            - setup_remote_docker
            - run:
               name: push deploy-docker
               command:  "sh .circleci/suitable.sh ./deploy-docker && (cd deploy-docker && /deploy) || echo not suitable"
               environment: 
                  REGISTRY: docker.io
                  IMAGE_NAME: cistuff/deploy-docker
            - run: 
               name: push deploy-pypi
               command: "sh .circleci/suitable.sh ./deploy-pypi && (cd deploy-pypi && /deploy) || echo not suitable"
               environment: 
                  REGISTRY: docker.io
                  IMAGE_NAME: cistuff/deploy-pypi
            - run: 
               name: push bump-version
               command: "sh .circleci/suitable.sh ./bump-version && (cd bump-version && /deploy) || echo not suitable"
               environment: 
                  REGISTRY: docker.io
                  IMAGE_NAME: cistuff/bump-version
    bump:
        docker:
            - image: cistuff/bump-version
        steps:
            - checkout
            - run:
               environment:
                  TAG_PREFIX: deploy-docker_
               name: bump deploy-docker
               command: "sh .circleci/suitable.sh ./deploy-docker && (cd deploy-docker && /bump) || echo not suitable"
            - run: 
               environment:
                  TAG_PREFIX: deploy-pypi_
               name: bump deploy-pypi
               command: "sh .circleci/suitable.sh ./deploy-pypi  && (cd deploy-pypi && /bump) || echo not suitable"
            - run:
               environment:
                  TAG_PREFIX: bump-version_
               name: bump bump-version
               command: "sh .circleci/suitable.sh ./bump-version  && (cd bump-version && /bump) || echo not suitable"

workflows:
    version: 2
    test_and_deploy:
        jobs:
            - bump
            - deploy:
                requires:
                    - bump