
version: 2
jobs:

    deploy:
        docker:
            - image: cistuff/deploy-docker
        environment:
            GIT_CHECK: ./
            REGISTRY: docker.io
        steps:
            - checkout
            - setup_remote_docker
            - run:
               name: push deploy-docker
               command: cd deploy-docker && /deploy
               environment: 
                  IMAGE_NAME: cistuff/deploy-docker
            - run: 
               name: push deploy-pypi
               command: cd deploy-pypi && /deploy
               environment: 
                  IMAGE_NAME: cistuff/deploy-pypi
            - run: 
               name: push bump-version
               command: cd bump-version && /deploy
               environment: 
                  IMAGE_NAME: cistuff/bump-version
            - run: 
               name: push bump
               command: cd bump && /deploy
               environment: 
                  IMAGE_NAME: cistuff/bump
    bump:
        environment:
            VERSION_FILE: ./VERSION
            GIT_CHECK: ./
        docker:
            - image: cistuff/bump:1.0.8
        steps:
            - checkout
            - run:
               environment:
                  TAG_PREFIX: deploy-docker_
               name: bump deploy-docker
               command: cd deploy-docker && /bump
            - run: 
               environment:
                  TAG_PREFIX: deploy-pypi_
               name: bump deploy-pypi
               command: cd deploy-pypi && /bump
            - run:
               environment:
                  TAG_PREFIX: bump-version_
               name: bump bump-version
               command: cd bump-version && /bump
            - run:
               environment:
                  TAG_PREFIX: bump_
               name: bump bump
               command: cd bump && /bump

workflows:
    version: 2
    test_and_deploy:
        jobs:
            - bump
            - deploy:
                requires:
                    - bump